### ISSUE TITLE
Cache tags on post.

### ISSUE THREAD

**Issue by stmtstk** [s-tip/stip-sns#101]
When a user post, S-TIP should parse (by using `extract_tags') post, add tag links and store `post` field into Feed class.
An original post (without tag liks) should be stored  into `post_org`.

---

Feed を表示するたびに post の内容から Tags を抽出して、post に対してリンクを付与している処理を行っています。
しかしながら、post の内容は変わらないのでこの処理は冗長です。
したがって、最初の post 解析時に link を付けた文字列を post フィールドに保存する処理を行います。
保存する場所としては 抽出ロジックは `extract_tags` を用いて [tags を取得した後](https://github.com/s-tip/stip-sns/blob/63c609068b2a1342e0c5ba0eed8ee194b5355ad1/src/feeds/views.py#L1435) が適切かと思います。

また、それ以外の箇所で `extract_tags` をコールしている箇所はすべて feed.post に変更しましょう。

**Comment by uchimrina** [comment]
https://github.com/s-tip/stip-sns/blob/8185509c165e1e4063703511b08194251ecdb028/src/feeds/views.py#L1447
Why are you using `post` instead of` feed.post` here?

https://github.com/s-tip/stip-sns/blob/8185509c165e1e4063703511b08194251ecdb028/src/feeds/views.py#L1410
Since the string length of the posted content is specified in the 1410th line, I think it is appropriate to use `feed.post` after the 1410th line.
Then, if line 1447 is `feed.post` and the location to save` post `and` post_org` is around line 1440, the posted content with the link will be recorded in STIX2.1.
So I think it should be saved around line 1459.

--- 
https://github.com/s-tip/stip-sns/blob/8185509c165e1e4063703511b08194251ecdb028/src/feeds/views.py#L1447
ここで`feed.post`ではなく`post`を使用している理由を教えてください。

https://github.com/s-tip/stip-sns/blob/8185509c165e1e4063703511b08194251ecdb028/src/feeds/views.py#L1410
1410 行目で投稿内容の文字列長を指定しているので、1410行目以降は`feed.post`を使うのが適切かと考えています。
そうすると、仮に上記1447行目を`feed.post`とした場合、`post `と `post_org` を保存する場所を1440行目あたりとすると、
リンク付きの post 内容が STIX2.1 へ記録されてしまうので、1459 行目あたりで保存するべきではないかと考えています。

**Comment by stmtstk** [comment]
Nice Catch, @uchimrina !!

Thanks for your awareness.

We should modify `extract_tags` below.

```
feed.post_org = post[:10240]
post_tags, feed.post = extract_tags(feed.post_org, False)
```

Call the `get_post_stix2_bundle` with `feed.post_org` instead of `post`.

---

気づきありがとうございます。
`extract_tags` を `False` 付きで呼び出して、戻り値を `feed.post` に格納。
`get_post_stix2_bundle` の呼び出し引数を `post` の代わりに `feed.post_org` としましょう。
